#define THREAD_GROUPS 10

RWTexture3D<float4> voxels;
uint3 voxelDimensions;

RWStructuredBuffer<float4> pixels;
uint pixelCount;  // = voxelDimensions.x * vD.y * vD.z;


uint To1D(uint3 id) {
	return id.x + id.y*(voxelDimensions.x) + id.z*(voxelDimensions.x * voxelDimensions.y);
}

#pragma kernel CSMain
[numthreads(THREAD_GROUPS, THREAD_GROUPS, THREAD_GROUPS)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // write from voxels texture into pixels array.
	pixels[To1D(id)] = voxels[id];
}
